my_snring=input('Введите текст:  ')
print(my_snring .upper())
print(my_snring.lower())
print(my_snring.replace(' '  ,'#'))
print(my_snring .replace(' ',''))
numbers=input('Введите количество символов в строке')
print('В строке', numbers,'символов')
letter=input('Введите первую букву строки')
print('Первая буква в строке- ',letter)
letter=input('Введите последнюю букву в строке')
print('Последняя буква в строке',letter)
